// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qp7jT9ycrBXbSQwhPW5HS99fUBzZQfE',
    appId: '1:560181459669:android:ddfc6a1922924cd152005c',
    messagingSenderId: '560181459669',
    projectId: 'acquired-router-428913-r8',
    storageBucket: 'acquired-router-428913-r8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8Nteiy0LXBGF3UXsyS1NyUxBCwWnuLY',
    appId: '1:560181459669:ios:720b6cda9d5f6cef52005c',
    messagingSenderId: '560181459669',
    projectId: 'acquired-router-428913-r8',
    storageBucket: 'acquired-router-428913-r8.appspot.com',
    iosBundleId: 'com.example.imtixon4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8Nteiy0LXBGF3UXsyS1NyUxBCwWnuLY',
    appId: '1:560181459669:ios:720b6cda9d5f6cef52005c',
    messagingSenderId: '560181459669',
    projectId: 'acquired-router-428913-r8',
    storageBucket: 'acquired-router-428913-r8.appspot.com',
    iosBundleId: 'com.example.imtixon4',
  );
}
